# Site settings
title: Brady's Developer Portfolio
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Full-stack developer with expertise in modern web technologies.
  Passionate about creating elegant solutions and clean code.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site

# GitHub Pages settings
remote_theme: b2a3e8/jekyll-theme-console

# Theme settings
style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true

# Header pages
header_pages:
  - index.md
  - about.md
  - resume.md
  - projects.md
  - blog.md
  - timeline.md
  - contact.md

# Footer
footer: 'Built with Jekyll & GitHub Pages | <a href="https://github.com/yourusername" target="_blank">GitHub</a>'

# Google Analytics (optional)
# google_analytics: UA-NNNNNNNN-N

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/blog/:title/"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "timeline"
    values:
      layout: "timeline"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
