#!/bin/bash
# Demo script to show the timeline functionality

echo "=== Portfolio Timeline Demo ==="
echo ""
echo "The timeline now automatically pulls from:"
echo "1. Projects with timeline.show: true"
echo "2. Blog posts with timeline.show: true"
echo ""
echo "=== Current Timeline Items ==="
echo ""
echo "📅 2024-01-15 - E-Commerce Platform (Project)"
echo "   💰 Impact: Processed $50K+ in transactions within first month"
echo "   🛠️  Tech: React, Node.js, PostgreSQL, Stripe, Docker"
echo ""
echo "📅 2024-01-10 - Modern JavaScript ES2024 Features (Article)"
echo "   📈 Impact: Featured in JavaScript Weekly newsletter"
echo "   🏷️  Tags: javascript, es2024, frontend, programming"
echo ""
echo "📅 2023-12-15 - Scalable React Architecture (Article)"
echo "   📈 Impact: Shared knowledge with 1000+ developers"
echo "   🏷️  Tags: react, architecture, frontend, best-practices"
echo ""
echo "📅 2023-11-20 - Task Management App (Project)"
echo "   📈 Impact: Improved team productivity by 40% in testing phase"
echo "   🛠️  Tech: Vue.js, Python, FastAPI, WebSockets, MongoDB"
echo ""
echo "📅 2023-09-10 - AI-Powered Code Review Tool (Project)"
echo "   📈 Impact: Reduced code review time by 60% for development teams"
echo "   🛠️  Tech: Python, TensorFlow, React, FastAPI, Docker, Git"
echo ""
echo "=== Timeline Features ==="
echo "✓ Automatic sorting by date (newest first)"
echo "✓ Unified projects and articles view"
echo "✓ Impact tracking for each milestone"
echo "✓ Technology/tag display"
echo "✓ Different icons for projects vs articles"
echo "✓ No separate timeline collection needed"
echo ""
echo "=== File Structure ==="
echo "• _projects/*.md (with timeline.show: true)"
echo "• _posts/*.md (with timeline.show: true)"
echo "• timeline.md (pulls from both collections)"
echo ""
echo "=== Timeline Metadata Format ==="
echo "timeline:"
echo "  show: true"
echo "  category: 'project' | 'article'"
echo "  milestone: 'Brief description'"
echo "  impact: 'Achievement or metrics'"
echo ""
echo "Demo complete! ✨"
